version: "3"
services:
  ccswebsite:
    image: ccswebsite
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == delboy
      restart_policy:
        condition: on-failure
    ports:
      - 5002:8080